<?php
/** @var \Mirasvit\CacheWarmer\Ui\Trace\Listing\Legend $block */
?>
<div class="mst-cache-warmer__info flushes">
    <div class="mst-trace-leggend">
        <div class="mst-trace-leggend__item mst-trace-backend">
            Backend action
        </div>
        <div class="mst-trace-leggend__item mst-trace-frontend">
            Frontend action
        </div>
        <div class="mst-trace-leggend__item mst-trace-cli">
            Cli action
        </div>
        <div class="mst-trace-leggend__item mst-trace-rest">
            REST action
        </div>
    </div>
</div>
