 <?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$current_currency_rate = $storeManager->getStore()->getCurrentCurrencyRate();
$currency_code = $storeManager->getStore()->getCurrentCurrencyCode();
$currency_model = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currency_code);
$currencySymbol = $currency_model->getCurrencySymbol();
$value_free = 100; //Value which is change on free  delivery message
 ?>
 <div class="priceFilter mb-5">
	<h6 class="heading-blog-title">Free Delivery</h6>
	 <p class="grey_text text-center">
		<strong>FREE worldwide delivery when you spend <?php echo $currencySymbol.number_format((float)$value_free*$current_currency_rate,2,'.',''	);  ?></strong>
	 </p>
 </div>