<?php
/**
 * @var $block \Agtech\Recently\Block\Viewproduct
 */
?>
 <h1>Most reseller Collection.....</h1>
      <ul>
<div>
	
	<?php echo "test";?>
 <?php
      $mostViewedProduct =  $block->getProductCollection(); ?>
      <h1>Most Viewed Collection.....</h1>
      <ul>
          <?php foreach ($mostViewedProduct as $viewedProduct) {
              ?>
              <li><?php echo $viewedProduct>getSku();?>--<?php echo $viewedProduct>getViews();?></li>
          <?php } ?>
</ul> 
</div>