<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?= /* @noEscape */ $class ?> option-<?= $block->escapeHtmlAttr($_option->getId()) ?> " >
    <label class="label" for="select_<?= $block->escapeHtmlAttr($_option->getId()) ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control select-for-custom">
        <?= $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()) :?>
            <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX) :?>
                <span id="options-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>

<script>
  require([
   'jquery',
   'domReady!'
   ], function ($) {
   $(document).ready(function () {
   $('select.product-custom-option').change(function(){
   $('option').each(function(){
  if($(this).val() == ''){
      $(this).remove();
	}
	var selectedOption = $(this).text();
   if (selectedOption.indexOf('+') > -1) {
   selectedOption = selectedOption.substring(0, selectedOption.indexOf('+'));
   $(this).text(selectedOption);
   } else if (selectedOption.indexOf('-') > -1) {
   selectedOption = selectedOption.substring(0, selectedOption.indexOf('-'));
   $(this).text(selectedOption);
   }
   });     
   });     
   });
    });
</script>
<script>
require(['jquery', 'jquery/ui'], function($){ 
  $('.product-add-form .field select').each(function(i, obj) {
    $(obj).find('option:eq(1)').prop('selected', true);
  });
});

</script> 
