<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';
?>
        <form class="form minisearch" id="search_mini_form"
              action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
                    <input id="search"
                           data-mage-init='{
                            "quickSearch": {
                                "formSelector": "#search_mini_form",
                                "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                "destinationSelector": "#search_autocomplete",
                                "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                            }
                        }'
                           type="text"
                           name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Search our products here...')) ?>"
                           class="input-text form-control"
                           maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"
                           onkeydown="if(event.keyCode === 13) { event.preventDefault(); document.getElementById('submitBtn').click(); }"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                    <button type="submit" title="Search" class="btn btn-primary">Search</button>
        </form>