<?php

$_product = $this->getProduct();

?>

<!--display FAQs for eSIM Card page:-->
<?php if ($_product->getSku()=='international-e-simcard' ) {  ?>


<!--=========================eSIM Compatible Devices for Desktop==============================-->
<div class="container mtop-50 text-center esim-desktop-FAQ">
<h3 class="heading text-center mb-5">eSIM Compatible Devices</h3>
<div class="faqPage card-body" id="esim-compatible-devices">                                    
    <ul class="accordion">
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Apple</a>
            <div class="inner" >
                <p>
					<ul>
						<li>iPhone 14</li>
						<li>iPhone 14 Plus</li>
						<li>iPhone 14 Pro</li>
						<li>iPhone 14 Pro Max</li>
						<li>iPhone 13</li>
						<li>iPhone 13 Pro</li>
						<li>iPhone 13 Pro Max</li>
						<li>iPhone 13 Mini</li>
						<li>iPhone 12</li>
						<li>iPhone 12 Mini</li>
						<li>iPhone 12 Pro</li>
						<li>iPhone 12 Pro Max</li>
						<li>iPhone 11</li>
						<li>iPhone 11 Pro</li>
						<li>iPhone 11 Pro Max</li>
						<li>iPhone XS</li>
						<li>iPhone XS Max</li>
						<li>iPhone XR</li>
						<li>iPhone SE (2020)</li>
						<li>iPhone SE (2022)</li>
						<li>iPad Air (3rd Generation)</li>
						<li>iPad Air (4th generation)</li>
						<li>iPad Pro 11 inch (1st generation)</li>
						<li>iPad Pro 11 inch (2nd generation)</li>
						<li>iPad Pro 11-inch (3rd generation)</li>
						<li>iPad Pro 12.9 inch (3rd generation)</li>
						<li>iPad Pro 12.9 inch (4th generation)</li>
						<li>iPad Pro 12.9-inch (5th generation)</li>
						<li>iPad (7th generation)</li>
						<li>iPad (8th generation)</li>
						<li>iPad (9th generation)</li>
						<li>iPad Mini (5th generation)</li>
						<li>iPad Mini (6th generation)</li>
					</ul>					
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Samsung</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Samsung Galaxy S23 Ultra</li>
						<li>Samsung Galaxy S23+</li>
						<li>Samsung Galaxy S23</li>
						<li>Samsung Galaxy S22 Ultra 5G</li>
						<li>Samsung Galaxy S22+ 5G</li>
						<li>Samsung Galaxy S22 5G</li>
						<li>Samsung Galaxy S21 Ultra 5G</li>
						<li>Samsung Galaxy S21 5G</li>
						<li>Samsung Galaxy S21+ 5G</li>
						<li>Samsung Galaxy S20</li>
						<li>Samsung Galaxy S20+</li>
						<li>Samsung Galaxy Note 20+</li>
						<li>Samsung Galaxy Note 20</li>
						<li>Samsung Galaxy Note 20 Ultra</li>
						<li>Samsung Galaxy Z Fold</li>
						<li>Samsung Galaxy Z Fold2</li>
						<li>Samsung Galaxy Z Fold3</li>
						<li>Samsung Galaxy Z Fold4</li>
						<li>Samsung Galaxy Z Flip</li>
						<li>Samsung Galaxy Z Flip3 5G</li>
						<li>Samsung Galaxy Z Flip4</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Google Pixel</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Google Pixel 3 & 3 XL*</li>
						<li>Google Pixel 3a & 3a XL*</li>
						<li>Google Pixel 4, 4a & 4 XL</li>
						<li>Google Pixel 5</li>
						<li>Google Pixel 6</li>
						<li>Google Pixel 6 Pro</li>
						<li>Google Pixel 6a</li>
						<li>Google Pixel 7</li>
						<li>Google Pixel 7 Pro</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">HAMMER</a>
            <div class="inner" >
                <p>
					<ul>
						<li>HAMMER Explorer PRO</li>
						<li>HAMMER Blade 3</li>
						<li>HAMMER Blade 5G</li>
						<li>myPhone NOW eSIM</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Motorola</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Motorola Razr 2019</li>
						<li>Motorola Razr 5G</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Huawei</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Huawei P40</li>
						<li>Huawei P40 Pro</li>
						<li>Huawei Mate 40 Pro</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">OnePlus</a>
            <div class="inner" >
                <p>
					<ul>
						<li>OnePlus 11 5G</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">OPPO</a>
            <div class="inner" >
                <p>
					<ul>
						<li>OPPO Find X3 Pro</li>
						<li>OPPO Find X5</li>
						<li>OPPO Find X5 Pro</li>
						<li>OPPO Reno A</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Sony</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Sony Xperia 10 III Lite</li>
						<li>Sony Xperia 10 IV</li>
						<li>Sony Xperia 1 IV</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Others</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Nuu Mobile X5</li>
						<li>Gemini PDA 4G+Wi-Fi</li>
						<li>Fairphone 4</li>
						<li>Xiaomi 12T Pro (Global)</li>
					</ul>
				</p>
            </div>
        </li>

    </ul>
</div>
	<p>Still not sure if your device supports eSIM? Contact our support via email/live chat. </p>
</div>


<!--=========================eSIM Compatible Devices for Mobile==============================-->
<div class="container mtop-50 text-center esim-mobile-FAQ">
<h3 class="heading text-center mb-5">eSIM Compatible Devices</h3>
<div class="faqPage card-body" id="esim-compatible-devices">                                    
    <ul class="accordion">
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Apple</a>
            <div class="inner" >
                <p>
					<ul>
						<li>iPhone 14</li>
						<li>iPhone 14 Plus</li>
						<li>iPhone 14 Pro</li>
						<li>iPhone 14 Pro Max</li>
						<li>iPhone 13</li>
						<li>iPhone 13 Pro</li>
						<li>iPhone 13 Pro Max</li>
						<li>iPhone 13 Mini</li>
						<li>iPhone 12</li>
						<li>iPhone 12 Mini</li>
						<li>iPhone 12 Pro</li>
						<li>iPhone 12 Pro Max</li>
						<li>iPhone 11</li>
						<li>iPhone 11 Pro</li>
						<li>iPhone 11 Pro Max</li>
						<li>iPhone XS</li>
						<li>iPhone XS Max</li>
						<li>iPhone XR</li>
						<li>iPhone SE (2020)</li>
						<li>iPhone SE (2022)</li>
						<li>iPad Air (3rd Generation)</li>
						<li>iPad Air (4th generation)</li>
						<li>iPad Pro 11 inch (1st generation)</li>
						<li>iPad Pro 11 inch (2nd generation)</li>
						<li>iPad Pro 11-inch (3rd generation)</li>
						<li>iPad Pro 12.9 inch (3rd generation)</li>
						<li>iPad Pro 12.9 inch (4th generation)</li>
						<li>iPad Pro 12.9-inch (5th generation)</li>
						<li>iPad (7th generation)</li>
						<li>iPad (8th generation)</li>
						<li>iPad (9th generation)</li>
						<li>iPad Mini (5th generation)</li>
						<li>iPad Mini (6th generation)</li>
					</ul>					
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Samsung</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Samsung Galaxy S23 Ultra</li>
						<li>Samsung Galaxy S23+</li>
						<li>Samsung Galaxy S23</li>
						<li>Samsung Galaxy S22 Ultra 5G</li>
						<li>Samsung Galaxy S22+ 5G</li>
						<li>Samsung Galaxy S22 5G</li>
						<li>Samsung Galaxy S21 Ultra 5G</li>
						<li>Samsung Galaxy S21 5G</li>
						<li>Samsung Galaxy S21+ 5G</li>
						<li>Samsung Galaxy S20</li>
						<li>Samsung Galaxy S20+</li>
						<li>Samsung Galaxy Note 20+</li>
						<li>Samsung Galaxy Note 20</li>
						<li>Samsung Galaxy Note 20 Ultra</li>
						<li>Samsung Galaxy Z Fold</li>
						<li>Samsung Galaxy Z Fold2</li>
						<li>Samsung Galaxy Z Fold3</li>
						<li>Samsung Galaxy Z Fold4</li>
						<li>Samsung Galaxy Z Flip</li>
						<li>Samsung Galaxy Z Flip3 5G</li>
						<li>Samsung Galaxy Z Flip4</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Google Pixel</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Google Pixel 3 & 3 XL*</li>
						<li>Google Pixel 3a & 3a XL*</li>
						<li>Google Pixel 4, 4a & 4 XL</li>
						<li>Google Pixel 5</li>
						<li>Google Pixel 6</li>
						<li>Google Pixel 6 Pro</li>
						<li>Google Pixel 6a</li>
						<li>Google Pixel 7</li>
						<li>Google Pixel 7 Pro</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">HAMMER</a>
            <div class="inner" >
                <p>
					<ul>
						<li>HAMMER Explorer PRO</li>
						<li>HAMMER Blade 3</li>
						<li>HAMMER Blade 5G</li>
						<li>myPhone NOW eSIM</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Motorola</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Motorola Razr 2019</li>
						<li>Motorola Razr 5G</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Huawei</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Huawei P40</li>
						<li>Huawei P40 Pro</li>
						<li>Huawei Mate 40 Pro</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">OnePlus</a>
            <div class="inner" >
                <p>
					<ul>
						<li>OnePlus 11 5G</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">OPPO</a>
            <div class="inner" >
                <p>
					<ul>
						<li>OPPO Find X3 Pro</li>
						<li>OPPO Find X5</li>
						<li>OPPO Find X5 Pro</li>
						<li>OPPO Reno A</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Sony</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Sony Xperia 10 III Lite</li>
						<li>Sony Xperia 10 IV</li>
						<li>Sony Xperia 1 IV</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Others</a>
            <div class="inner" >
                <p>
					<ul>
						<li>Nuu Mobile X5</li>
						<li>Gemini PDA 4G+Wi-Fi</li>
						<li>Fairphone 4</li>
						<li>Xiaomi 12T Pro (Global)</li>
					</ul>
				</p>
            </div>
        </li>

    </ul>
</div>
	<p>Still not sure if your device supports eSIM? Contact our support via email/live chat. </p>
</div>


<!--========================== Desktop FAQs ========================-->

<div class="container text-center esim-desktop-FAQ">
<h3 class="heading text-center mt-5 mb-5">Frequently asked questions</h3>
<div class="faqPage card-body" id="faqs">                                    
    <ul class="accordion">
		<li>
            <a class="toggleAcc" href="javascript:void(0);">What is eSIM?</a>
            <div class="inner" >
                <p>An eSIM is a virtual SIM card directly integrated into your device by the provider. It does not need to be inserted into your smartphone and can be programmed remotely. The operation of the eSIM is identical to a physical SIM card. Only the installation of the eSIM profile and the activation is slightly different. When activating your eSIM you will require wifi or data connection.</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Is there a phone number, voice, SMS, and data included with my WorldSIMeSIM Plus purchase?</a>
            <div class="inner" >
                <p>Yes, WorldSIM eSIM comes with a UK mobile and supports Voice calls, data, and SMS etcas long as you have balance in your account. You can buy data plans and or recharge your eSIM by purchasing airtime from the <a href="<?php $this->getUrl('') ?>top-up">Top-Up page</a> on our website. Once you have downloaded your eSIM and its connected to an operator you can dial the following numbers to get information on your account;
					<br/>133 – Returns your mobile number
					<br/>187 – Returns your account balance 
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">How do I activate eSIM on my iPhone using QR Code</a>
            <div class="inner" >
                <p>
					1. 	Go to Settings<br/>
					2.	Tap either Cellular or Mobile Data<br/>
					3.	Add Data Plan or Add Cellular Plan or Add eSIM<br/>
					4.	Scan QR code (Ensure phone is connected to mobile data/Wi-Fi while scanning)<br/>
					5.	Follow step-by-step process<br/>
					6.	Your mobile plan will be downloaded and activated on your eSIM<br/>
					7.	Restart your phone – you may have to wait for 3 minutes for a network signal
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">How do I activate eSIM on my Samsung (Android) using QR Code</a>
            <div class="inner" >
                <p>
					1.	Go to Settings > Connections > SIM card manager<br/>
					2.	Tap Add mobile plan or Add eSIM<br/>
					3.	Tap Add using QR code<br/>
					4.	Scan the QR code (Ensure phone is connected to mobile data/Wi-Fi while scanning)<br/>
					5.	Follow step-by-step process<br/>
					6.	Your mobile plan will be downloaded and activated on your eSIM<br/>
					7.	Restart your phone – you may have to wait for 3 minutes for network signal<br/>
					8.	Ensure you allow your eSIM by clicking on the toggle until its blue<br/>
					9.	From the menu choose your ‘Preferred Sim’ from which to make and receive calls from. Both your existing sim and new eSIM will be able to receive incoming calls, unless you decide to switch one off.
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">I cannot scan the QR Code, what do I do?</a>
            <div class="inner" >
                <p>
					If you cannot scan the provided QR Code, you can install the eSIM by entering details manually. You will be asked to enter the SM-DP+ Address, Activation Code all of which are included in the eSIM confirmation details provided after purchase.
					Please follow our guides on how to install an eSIM manually:
					<ul>
						<li>iOS eSIM Installation Guide</li>
						<li>Android eSIM Installation Guide</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Is the activation immediate?</a>
            <div class="inner" >
                <p>Yes, your eSIM is activated immediately if you have arrived at your destination already. If you are still abroad, please install the eSIM via the QR code either once you have arrived at your destination or shortly before the flight as the validity starts counting from the time of installation. You will need a wifi or data connection to install the eSIM</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Can I make calls & send SMS with an eSIM?</a>
            <div class="inner" >
                <p>Yes, with WorldSIM eSIM you can use data, voice calls, SMS etc just like a physical SIM card. </p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Is my smartphone eSIM-compatible?</a>
            <div class="inner" >
                <p>You can check this by following the steps: Go to Settings> Connections> SIM card manager> Add Mobile plan. If the “Add Mobile plan” of ‘Add eSIM’ is available, it should mean that your device supports eSIMs. You can also tap “IMEI” in the search bar of your settings, and the option “IMEI information” (or similar) should show up. Alternatively you can contact your handset provider to check if your 	model is eSIM compatible or not. 
				<br/>**Note that - country and carrier-specific restrictions may apply.</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">How can I contact customer support?</a>
            <div class="inner" >
                <p>Our team will remain at your disposal via our
					1) Live Chat:  <a href="https://www.worldsim.com/live-chat">https://www.worldsim.com/live-chat</a>
					2) Email support: <a href="mailto:customerservice@worldsim.com">customerservice@worldsim.com</a>
				</p>
            </div>
        </li>
		
		
		
		
        <!--<li>
            <a class="toggleAcc" href="javascript:void(0);">How to check if my iOS device is eSIM compatible and carrier unlocked?</a>
            <div class="inner" >
                <p>To learn if your iOS device is eSIM compatible and carrier unlocked, you will need to:<br/>
                <ul class="faq-inner-list">
                  <li>Go to Settings> General> About.</li>
                  <li>Scroll down to view the “Carrier lock” section.</li>
                  <li>It should say “NO SIM restrictions”, which means that the device is unlocked.</li>
                  <li>Scroll down to view the “AVAILABLE SIM” (iOS 15 and newer) or “DIGITAL SIM”(older iOS versions) section. It should contain an IMEI under AVAILABLE SIM or DIGITAL SIM, which means that the device is eSIM compatible.</li>
                </ul>Depending on your device’s capability, if you have more than one SIM on the device, you may need to temporarily disable/remove one of the SIM cards before trying to download the eSIM.</p> 
            </div>
        </li>-->

        <!--<li>
            <a class="toggleAcc" href="javascript:void(0);">How to check if my Android device is eSIM compatible?</a>
            <div class="inner" >
                <p>Your bundle is valid for 7 days, post 7 days the sim can be recharged locally from Ooredoo website or from any authorised store Ooredoo</p>
            </div>
        </li>

        <li>
            <a class="toggleAcc" href="javascript:void(0);">How long does it takes to activate an eSIM? </a>
            <div class="inner" >
                <p>Need to ensure that you have an unlocked 3G/4G/5G handset which is not locked by the operator and have minimum 3G capabilities.</p>
            </div>
        </li>

        <li>
            <a class="toggleAcc" href="javascript:void(0);">Can I use eSIM on locked iPhone?</a>
            <div class="inner" >
                <p>Yes you can; simply select your desired product from the available range and recharge from Ooredoo website: or from Ooredoo App or from any authorised store Ooredoo</p>
            </div>
        </li>

        <li>
            <a class="toggleAcc" href="javascript:void(0);">What are eSIM compatible handsets?</a>
            <div class="inner" >
                <p>Just dial *129# and you will get a notification message about the available balance.</p>
            </div>
        </li>-->
        

    </ul>
</div>
</div>


<!--================Mobile View FAQs main=========================-->
<div class="container text-center esim-mobile-FAQ">
<h3 class="heading text-center mt-5 mb-5">Frequently asked questions</h3>
<div class="faqPage card-body" id="faqs">                                    
    <ul class="accordion">
		<li>
            <a class="toggleAcc" href="javascript:void(0);">What is eSIM?</a>
            <div class="inner" >
                <p>An eSIM is a virtual SIM card directly integrated into your device by the provider. It does not need to be inserted into your smartphone and can be programmed remotely. The operation of the eSIM is identical to a physical SIM card. Only the installation of the eSIM profile and the activation is slightly different. When activating your eSIM you will require wifi or data connection.</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Is there a phone number, voice, </br> SMS, and data included with </br> my WorldSIMeSIM Plus purchase?</a>
            <div class="inner" >
                <p>Yes, WorldSIM eSIM comes with a UK mobile and supports Voice calls, data, and SMS etcas long as you have balance in your account. You can buy data plans and or recharge your eSIM by purchasing airtime from the <a href="<?php $this->getUrl('') ?>top-up">Top-Up page</a> on our website. Once you have downloaded your eSIM and its connected to an operator you can dial the following numbers to get information on your account;
					<br/>133 – Returns your mobile number
					<br/>187 – Returns your account balance 
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">How do I activate eSIM on </br> my iPhone using QR Code</a>
            <div class="inner" >
                <p>
					1. 	Go to Settings<br/>
					2.	Tap either Cellular or Mobile Data<br/>
					3.	Add Data Plan or Add Cellular Plan or Add eSIM<br/>
					4.	Scan QR code (Ensure phone is connected to mobile data/Wi-Fi while scanning)<br/>
					5.	Follow step-by-step process<br/>
					6.	Your mobile plan will be downloaded and activated on your eSIM<br/>
					7.	Restart your phone – you may have to wait for 3 minutes for a network signal
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">How do I activate eSIM on </br> my Samsung (Android) </br> using QR Code</a>
            <div class="inner" >
                <p>
					1.	Go to Settings > Connections > SIM card manager<br/>
					2.	Tap Add mobile plan or Add eSIM<br/>
					3.	Tap Add using QR code<br/>
					4.	Scan the QR code (Ensure phone is connected to mobile data/Wi-Fi while scanning)<br/>
					5.	Follow step-by-step process<br/>
					6.	Your mobile plan will be downloaded and activated on your eSIM<br/>
					7.	Restart your phone – you may have to wait for 3 minutes for network signal<br/>
					8.	Ensure you allow your eSIM by clicking on the toggle until its blue<br/>
					9.	From the menu choose your ‘Preferred Sim’ from which to make and receive calls from. Both your existing sim and new eSIM will be able to receive incoming calls, unless you decide to switch one off.
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">I cannot scan the QR Code,</br> what do I do?</a>
            <div class="inner" >
                <p>
					If you cannot scan the provided QR Code, you can install the eSIM by entering details manually. You will be asked to enter the SM-DP+ Address, Activation Code all of which are included in the eSIM confirmation details provided after purchase.
					Please follow our guides on how to install an eSIM manually:
					<ul>
						<li>iOS eSIM Installation Guide</li>
						<li>Android eSIM Installation Guide</li>
					</ul>
				</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Is the activation immediate?</a>
            <div class="inner" >
                <p>Yes, your eSIM is activated immediately if you have arrived at your destination already. If you are still abroad, please install the eSIM via the QR code either once you have arrived at your destination or shortly before the flight as the validity starts counting from the time of installation. You will need a wifi or data connection to install the eSIM</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Can I make calls & send SMS </br> with an eSIM?</a>
            <div class="inner" >
                <p>Yes, with WorldSIM eSIM you can use data, voice calls, SMS etc just like a physical SIM card. </p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">Is my smartphone is <br> eSIM-compatible?</a>
            <div class="inner" >
                <p>You can check this by following the steps: Go to Settings> Connections> SIM card manager> Add Mobile plan. If the “Add Mobile plan” of ‘Add eSIM’ is available, it should mean that your device supports eSIMs. You can also tap “IMEI” in the search bar of your settings, and the option “IMEI information” (or similar) should show up. Alternatively you can contact your handset provider to check if your 	model is eSIM compatible or not. 
				<br/>**Note that - country and carrier-specific restrictions may apply.</p>
            </div>
        </li>
		<li>
            <a class="toggleAcc" href="javascript:void(0);">How can I contact with <br> customer support?</a>
            <div class="inner" >
                <p>Our team will remain at your disposal via our
					1) Live Chat:  <a href="https://www.worldsim.com/live-chat">https://www.worldsim.com/live-chat</a>
					2) Email support: <a href="mailto:customerservice@worldsim.com">customerservice@worldsim.com</a>
				</p>
            </div>
        </li>
		
		
		
		
        <!--<li>
            <a class="toggleAcc" href="javascript:void(0);">How to check if my iOS device is eSIM compatible and carrier unlocked?</a>
            <div class="inner" >
                <p>To learn if your iOS device is eSIM compatible and carrier unlocked, you will need to:<br/>
                <ul class="faq-inner-list">
                  <li>Go to Settings> General> About.</li>
                  <li>Scroll down to view the “Carrier lock” section.</li>
                  <li>It should say “NO SIM restrictions”, which means that the device is unlocked.</li>
                  <li>Scroll down to view the “AVAILABLE SIM” (iOS 15 and newer) or “DIGITAL SIM”(older iOS versions) section. It should contain an IMEI under AVAILABLE SIM or DIGITAL SIM, which means that the device is eSIM compatible.</li>
                </ul>Depending on your device’s capability, if you have more than one SIM on the device, you may need to temporarily disable/remove one of the SIM cards before trying to download the eSIM.</p> 
            </div>
        </li>-->

        <!--<li>
            <a class="toggleAcc" href="javascript:void(0);">How to check if my Android device is eSIM compatible?</a>
            <div class="inner" >
                <p>Your bundle is valid for 7 days, post 7 days the sim can be recharged locally from Ooredoo website or from any authorised store Ooredoo</p>
            </div>
        </li>

        <li>
            <a class="toggleAcc" href="javascript:void(0);">How long does it takes to activate an eSIM? </a>
            <div class="inner" >
                <p>Need to ensure that you have an unlocked 3G/4G/5G handset which is not locked by the operator and have minimum 3G capabilities.</p>
            </div>
        </li>

        <li>
            <a class="toggleAcc" href="javascript:void(0);">Can I use eSIM on locked iPhone?</a>
            <div class="inner" >
                <p>Yes you can; simply select your desired product from the available range and recharge from Ooredoo website: or from Ooredoo App or from any authorised store Ooredoo</p>
            </div>
        </li>

        <li>
            <a class="toggleAcc" href="javascript:void(0);">What are eSIM compatible handsets?</a>
            <div class="inner" >
                <p>Just dial *129# and you will get a notification message about the available balance.</p>
            </div>
        </li>-->
        

    </ul>
</div>
</div>






<style type="text/css">
.faq-inner-list li{
      list-style: disc !important;
}
.mtop-50{
      margin-top: -50px !important;
	  margin-bottom: 20px;
}
.faq-subheading{
    font-size: 24px;
    color: #696969;
}
.faqPage{
    text-align: left;
}
.faqPage .accordion li.arrowMine .toggleAcc {
    background: url(<?php echo $block->getViewFileUrl('images/faq_mins.gif'); ?>)97% 24px no-repeat;
}
.faqPage .toggleAcc {
    font-size: 18px;
    color: #000;
    display: block;
    border-bottom: 1px solid #e7e7e7;
    padding: 17px 38px;
    background: url(<?php echo $block->getViewFileUrl('images/faq_plus.gif'); ?>)97% 24px no-repeat;
}

.faqPage .accordion .inner {
    margin: 20px 0;
}
.faqPage .accordion li p {
    font-size: 16px;
    padding: 0 24px;
    line-height: 28px;
}
.inner {
    padding-left: 1em;
    overflow: hidden;
    display: none;
}
.faqPage .accordion {
    padding-left: 0;
    margin-bottom: 0;
}
.faqPage .accordion li {
    list-style: none;
}

.add_to_basket_button_click{
	color: #ffffff !important;
}

#include_esim {
    pointer-events: none;
}
    
    /*@media(max-width:766px){
        
    }*/
</style>
<script type="text/javascript">
      require(['jquery'], function ($) { 
            $(document).ready(function() {
                $('.toggleAcc').click(function() { 
                    var $this = $(this);
                    $('li').removeClass('arrowMine')                      
                    if ($(this).next().hasClass('showAcc')) {
                        $(this).next().removeClass('showAcc');
                        $(this).next().slideUp(350);
                    } else {
                        $(this).parent().parent().find('li .inner').removeClass('showAcc');
                        $(this).parent().parent().find('li .inner').slideUp(350);
                        $(this).next().toggleClass('showAcc');
                        $(this).next().slideToggle(350);
                        $(this).parent('li').toggleClass('arrowMine') 
                    }
                });
            });          
	 });
</script>
<?php }else{ ?>

<div class="container">
	<?php echo $_product->getData('content_slider1'); ?>
</div>

<?php } ?>