<?php
$agtechobjBlock = $block->getLayout()->createBlock('Agtech\ProductObject\Block\Objproductconv');
$storeManager = $agtechobjBlock->getStoremangerInter();
$cartHelper = $agtechobjBlock->getCarthelperObj();

// Dynamically loaded product
$skuIds = [
    'data-bundle-topup-new',
    'data-sim-bundle-new',
    'data-esim-bundle-new',
];

$productModels = [];
$productIds = [];
$customOptions = [];

foreach ($skuIds as $sku) {
    $productModel = $agtechobjBlock->getproductModel()->loadByAttribute('sku', $sku);
    $productId = $productModel->getId();
    $customOption = $agtechobjBlock->getproductOptionModel()->getProductOptionCollection($productModel);

    $productModels[] = $productModel;
    $productIds[] = $productId;
    $customOptions[] = $customOption;
}
$product_model_topup = $productModels[0];
$product_id_topup = $productIds[0];
$customOptions_topup = $customOptions[0];

$product_model_new_physical_sim = $productModels[1];
$product_id_new_physical_sim = $productIds[1];
$customOptions_new_physical_sim = $customOptions[1];

$product_model_new_e_sim = $productModels[2];
$product_id_new_e_sim = $productIds[2];
$customOptions_new_e_sim = $customOptions[2];

// end Dynamically loaded product

$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
$currencyFactory = $agtechobjBlock->getcurrencyFactoryModel()->create()->load($currencyCode);
$storeCode = $storeManager->getStore()->getCode();
$storeId = $storeManager->getStore()->getId();
/* Currncy Code*/
$currencySymbol = $currencyFactory->getCurrencySymbol(); /* Currency Symbol */
$currencies = $storeManager->getStore()->getAllowedCurrencies();
$baseCurrencyCode = $storeManager->getStore()->getBaseCurrencyCode();
$defaultCurrencies = $storeManager->getStore()->getBaseCurrency();
$Current_CurrencyCode = $storeManager->getStore()->getCurrentCurrencyCode();

$convRate = 1;
$rates = $currencyFactory->getCurrencyRates($defaultCurrencies, $currencies);
$rates_currency = $storeManager->getStore()->getCurrentCurrencyRate();
$StoreConvRate = $rates_currency;

$file_name_with_path = "./media/tariff/databundle_countries.json";
$databundle_countries = file_get_contents($file_name_with_path);
$databundle_countries = json_decode($databundle_countries);
//$file_name_with_path = $this->getUrl('')."json/databundle_plans_info.json";
//$db_info =  file_get_contents($file_name_with_path);
//$db_info =  json_decode($db_info);

if ($storeId == 1):
    $defaultCountry = "United Kingdom";
else:
    $defaultCountry = "United States of America";
endif;


//new
$newblock = $this->getLayout()->createBlock("Worldsim\Databundle\Block\Frontend\Country\Country");

$countryData = $newblock->getCountryData();
$singleCountry = $countryData['singleCountryArray'];
$multipleCountry = $countryData['multipleCountryArray'];

$singleCountry = array_map("unserialize", array_unique(array_map("serialize", $singleCountry)));
$multipleCountry = array_map("unserialize", array_unique(array_map("serialize", $multipleCountry)));


$getplanData = $newblock->getPlanData();
$url = 'https://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
?>
<section class="bundleData mb-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-12">
                <form action="">
                    <div class="tabs">
                        <ul class="nav nav-tabs justify-content-center border-0 m-auto">
                            <li class="w-50"><a data-toggle="tab" class="d-block text-center firstTab active"
                                    id="popularCountries" href="#">Popular Countries</a></li>
                            <li class="w-50"><a data-toggle="tab" class=" text-center d-block secondTab"
                                    id="multipleCountries" href="#">Multiple Countries</a></li>
                        </ul>

                        <div class="tab-content">
                            <div id="popularCountriesshow" class="tab-pane fade active show">
                                <div class="outer-country">
                                    <ul class="flagList d-flex flex-wrap justify-content-center popular-country-show"
                                        role="tablist">
                                        <li><label data-tag="tab1"><input type="radio" name="country" value="United States of America"
                                                    data-target="#italyTabs">
                                                <span class="flagData italy text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">USA</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab2"><input type="radio" name="country" value="France"
                                                    data-target="#thailandTabs">
                                                <span class="flagData thailand text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">France</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab3"><input type="radio" value="United Arab Emirates" name="country">
                                                <span class="flagData canada text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">UAE</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab4"><input type="radio" value="Turkey" name="country">
                                                <span class="flagData mexico text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Turkey</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab5"><input type="radio" value="Thailand" name="country">
                                                <span class="flagData turkey text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Thailand</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab6"><input type="radio" value="Germany" name="country">
                                                <span class="flagData germany text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Germany</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab7"><input type="radio" value="United Kingdom" name="country">
                                                <span class="flagData israel text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">UK</i>
                                                </span>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <div class="outer-country">
                                    <ul class="flagList d-flex flex-wrap justify-content-center multiple-country-show"
                                        role="tablist" style="display:none !important;">
                                        <li><label data-tag="tab8"><input type="radio" name="country" value="Global">
                                                <span class="flagData global text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Global</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab9"><input type="radio" name="country" value="Asia">
                                                <span class="flagData asia text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Asia</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab10"><input type="radio" name="country" value="Africa">
                                                <span class="flagData africa text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Africa </i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab11"><input type="radio" name="country" value="Europe">
                                                <span class="flagData europe text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Europe </i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab12"><input type="radio" name="country"
                                                    value="Middle East">
                                                <span class="flagData middleEast text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">Middle East </i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab13"><input type="radio" name="country"
                                                    value="North America">
                                                <span class="flagData northAmerica text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">North America</i>
                                                </span>
                                            </label>
                                        </li>
                                        <li><label data-tag="tab14"><input type="radio" name="country"
                                                    value="South America">
                                                <span class="flagData southAmerica text-center">
                                                    <img
                                                        src="<?php echo $block->getViewFileUrl('images/bundle-data/sprite.png'); ?>">
                                                    <i class="d-block">South America</i>
                                                </span>
                                            </label>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tab-content">
                                    <div id="tab1" class="listTabs active">
                                        <p class="tags single-country"  style="line-height: 20px;">Select Country:</p>
                                        <div class="country_autoSelect d-flex justify-content-center">
                                            <select class="tags single-country" id="databundle_topup_location"name="single" style="background-image: url(<?php echo $block->getViewFileUrl('images/bundle-data/searchicon.png'); ?>);background-size: initial;    background-position: 16px 15px;    background-repeat: no-repeat; padding: 12px 20px 12px 45px;">
                                                <?php foreach ($singleCountry as $countryData) { ?>
                                                    <option value="<?php echo $countryData['country']; ?>"><?php echo $countryData['country']; ?></option>
                                                <?php } ?>
                                            </select>
                                            <select class="tags multiple-country"
                                                id="databundle_topup_location_multiple" name="multiple">
                                                <?php foreach ($multipleCountry as $countryData) { ?>
                                                    <option value="<?php echo $countryData['country']; ?>"><?php echo $countryData['country']; ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                        <div class="validityBlock">
                                            <div class="row d-flex justify-content-center plan-content" id="totalcost">
                                            </div>
                                        </div>

                                        <div class="roamingcountry_autoSelect" id="roamingcountry_autoSelect">
                                            <!--<h3>You can also use this bundle in list of following countries: </h3>-->
                                            <!--<select class="tags" id="databundle_roamingcountries">
                                            </select>-->
                                            <div class="faqPage card-body" id="faqs">                                    
                                                <ul class="accordion">
                                                    <li>
                                                        <a class="toggleAcc" href="javascript:void(0);">You can also use this bundle in list of following countries:</a>
                                                        <div class="inner">
                                                            <p>
                                                                <ul class="roaming_countries_list" id="databundle_roamingcountries"></ul>
                                                            </p>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>

                                        <div class="priceTable text-center" id="preload">
                                            <h2>Total Cost: <!-- &#163; --><span class="span1 total-cost"
                                                    id="total_cost">0.0</span></h2>
                                            <div>
                                                <a style="pointer-events: none; cursor: pointer;" data-toggle="modal"
                                                    data-target="#popup-modal" data-id="model" href="javascript:;"
                                                    class="proceedBtn" id="click-me">Proceed</a>
                                            </div>
                                            <div class="modal simModal fade" id="popup-modal" style="opacity: 1;">
                                                <div class="modal-dialog modal-lg modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <!-- Modal body -->
                                                        <div class="modal-body text-left">
                                                            <button type="button" class="close"
                                                                data-dismiss="modal">&times;</button>
                                                            <div class="dataCard">
                                                                <div class="dataGrid d-flex" id="existing-customer">
                                                                    <div class="leftradio"><label
                                                                            class="checkbox"><input type="radio"
                                                                                name="customers"
                                                                                id="mob_cus_id_btn"><span></span></label>
                                                                    </div>
                                                                    <div class="rightBar"><label>Existing
                                                                            Customers</label>
                                                                        <input type="text" class="form-control"
                                                                            name="Mobile"
                                                                            placeholder="Enter Mobile number/ICCID"
                                                                            id="mob_cus_id_mobile">
                                                                    </div>
                                                                </div>
                                                                <div class="dataGrid d-flex" id="new-customer">
                                                                    <div class="leftradio"><label class="checkbox">
                                                                            <input type="radio" name="customers"
                                                                                id="include_sim_new"><span></span></label>
                                                                    </div>
                                                                    <div class="rightBar">
                                                                        <label class="pb-3">New to WorldSIM? Please
                                                                            Select your preferred SIM card</label>
                                                                        <a href="javascript:;"
                                                                            class="simBtn mr-2 active"
                                                                            id="esim_button">eSIM Card</a>
                                                                        <a href="javascript:;" class="simBtn"
                                                                            id="physicalsim_button">Physical SIM
                                                                            Card</a>
                                                                    </div>
                                                                </div>
                                                                <div class="text-center mt-5">
                                                                    <a class="proceedBtn bundle_add_btn_new"
                                                                        id="bundle_add_btn" href="javascript:;">Add to
                                                                        basket</a>
                                                                </div>
                                                                <div class="col-md-12 mt-3 text-center"
                                                                    id="databundle_topup_msg_new" style="color:red;">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<div class="debug-forms" style="display:none">
<form class="ajax_custom_form_for_new " data-role="tocart-form"
    action="<?php echo $cartHelper->getAddUrl($product_model_new_e_sim); ?>" method="post">
    <?php
    foreach ($customOptions_new_e_sim as $option) {
        $values = $option->getValues();
        if ($option->getTitle() == "Bundle") {
            echo "<select class='bundle_sim_option_choose product-custom-option data_bundle_new_e_sim' name='options[" . $option->getId() . "]'data-selector='options[" . $option->getId() . "]' >";
            if ($values) {
                foreach ($values as $value) {
                    $credit_value = $value->getId();
                    echo "<option value=" . $credit_value . ">" . $value->getTitle() . "</option>";
                }
            }
        }
        if ($option->getTitle() == "Bundle Country") {
            echo "<input class='country_select_drop' name=options[" . $option->getId() . "] type='text'>";
        }
        if ($option->getTitle() == "SIM Type") { ?>
            <?php if (strpos($url, '/data-bundles') !== false) { ?>
                <?php echo "<input name=options[" . $option->getId() . "] type='text' value='International eSIM Card'>";
            } else {
                echo "<input name=options[" . $option->getId() . "] type='text' value='Data SIM Card'>";
            }
        }
    }
    ?>
    <div class="btn">
        <button type="submit" title="Add to Cart" class="action tocart primary new_esimcard_cart_add ">
            <span>Add to Cart</span>
        </button>
    </div>
</form>
<form class="ajax_custom_form_for_new " data-role="tocart-form"
    action="<?php echo $cartHelper->getAddUrl($product_model_new_physical_sim); ?>" method="post">
    <?php

    foreach ($customOptions_new_physical_sim as $option) {
        $values = $option->getValues();
        if ($option->getTitle() == "Bundle") {

            echo "<select class='bundle_sim_option_choose product-custom-option data_bundle_new_physical_sim' name='options[" . $option->getId() . "]'data-selector='options[" . $option->getId() . "]' >";
            if ($values) {
                foreach ($values as $value) {
                    $credit_value = $value->getId();
                    echo "<option value=" . $credit_value . ">" . $value->getTitle() . "</option>";
                }
            }

        }
        if ($option->getTitle() == "Bundle Country") {
            echo "<input class='country_select_drop' name=options[" . $option->getId() . "] type='text'>";
        }
        if ($option->getTitle() == "SIM Type") { ?>
            <?php if (strpos($url, '/data-bundles') !== false) { ?>
                <?php echo "<input name=options[" . $option->getId() . "] type='text' value='International SIM Card'>";
            } else {
                echo "<input name=options[" . $option->getId() . "] type='text' value='Data SIM Card'>";
            }
        }

    }
    ?>
    <div class="btn">
        <button type="submit" title="Add to Cart" class="action tocart primary new_simcard_cart_add ">
            <span>Add to Cart</span>
        </button>
    </div>
</form>
<form data-role="tocart-form" action="<?php echo $cartHelper->getAddUrl($product_model_topup); ?>" method="post" class="ajax_custom_form_for_topup ">
    <?php
    foreach ($customOptions_topup as $option) {
        $values = $option->getValues();
        if ($option->getTitle() == "Bundle") {
            echo "<select class='bundle_sim_option_choose product-custom-option data_bundle_topup' name='options[" . $option->getId() . "]' data-selector='options[" . $option->getId() . "]' >";
            if ($values) {
                foreach ($values as $value) {
                    $credit_value = $value->getId();
                    echo "<option value=" . $credit_value . " >" . $value->getTitle() . "</option>";
                }
            }

            echo "</select>";
        }
        if ($option->getTitle() == "Bundle Country") {
            echo "<input class='country_select_drop' name=options[" . $option->getId() . "] type='text'>";
        }
        if ($option->getId() == "2") {
            echo "<input id='mob_cus_id_orig' name=options[" . $option->getId() . "] type='text' >";
        }
    }
    ?>
    <div class="btn">
        <button type="submit" title="Add to Cart" class="action tocart primary bundle_topup_cart_add">
            <span>Add to Cart</span>
        </button>
    </div>
</form>
</div>

<style>
    .page-main{
        padding-top: 0px;
    }
    div#databundle_topup_msg {
        color: #ff0000;
    }
    .faqPage{
        text-align: left;
    }
    .faqPage .accordion li.arrowMine .toggleAcc {
        background: url(<?php echo $block->getViewFileUrl('images/faq_mins.gif'); ?>)97% 24px no-repeat;
    }
    .faqPage .toggleAcc {
        font-size: 18px;
        color: #000;
        display: block;
        border-bottom: 1px solid #e7e7e7;
        padding: 17px 38px;
        background: url(<?php echo $block->getViewFileUrl('images/faq_plus.gif'); ?>)97% 24px no-repeat;
    }
    
    .faqPage .accordion .inner {
        margin: 20px 0;
    }
    .faqPage .accordion li p {
        font-size: 16px;
        padding: 0 24px;
        line-height: 28px;
    }
    .inner {
        padding-left: 1em;
        overflow: hidden;
        display: none;
    }
    .faqPage .accordion {
        padding-left: 0;
        margin-bottom: 0;
    }
    .faqPage .accordion li {
        list-style: none;
    }
    
    .roaming_countries_list{
        list-style: none;
        -webkit-column-count: 3;
        -moz-column-count: 3;
        column-count: 3;
    }
    @media(max-width:766px){
        .roaming_countries_list{
            list-style: none;
            -webkit-column-count: 2;
            -moz-column-count: 2;
            column-count: 2;
        }
    }
</style>

<script type="text/javascript">
    require(['jquery'], function ($) {

        $(document).ready(function () {
            
            $('.toggleAcc').click(function() { 
                var $this = $(this);
                $('li').removeClass('arrowMine')                      
                if ($(this).next().hasClass('showAcc')) {
                    $(this).next().removeClass('showAcc');
                    $(this).next().slideUp(350);
                } else {
                    $(this).parent().parent().find('li .inner').removeClass('showAcc');
                    $(this).parent().parent().find('li .inner').slideUp(350);
                    $(this).next().toggleClass('showAcc');
                    $(this).next().slideToggle(350);
                    $(this).parent('li').toggleClass('arrowMine') 
                }
            });

            $('.simBtn').on('click', function () {
                $('.simBtn').removeClass('active');
                $(this).addClass('active');
            })
            
            var locationValue = (new URL(location.href)).searchParams.get('country');

            if (locationValue != null) {
                $('input:radio[value="'+locationValue+'"]').prop('checked', true);
                $('#databundle_topup_location').val(locationValue).trigger('change');
                $('.multiple-country').attr("style", "display:none !important");
            }else{
                $('input:radio[value="Italy"]').prop('checked', true);
                $('#databundle_topup_location').val('Italy').trigger('change');
                $('.multiple-country').attr("style", "display:none !important");
            }

            $("#multipleCountries").click(function () {
                $('.popular-country-show').attr("style", "display:none !important");
                $('.single-country').attr("style", "display:none !important");
                $('.multiple-country-show').removeAttr("style");
                $('.multiple-country').removeAttr("style");
                $('#popularCountries').removeClass('active');
                $("input:radio[value='Global']").prop('checked', true);
                $('#databundle_topup_location_multiple').val('Global').trigger('change');
            });

            $("#popularCountries").click(function () {
                $('.multiple-country-show').attr("style", "display:none !important");
                $('.multiple-country').attr("style", "display:none !important");
                $('.popular-country-show').removeAttr("style");
                $('.single-country').removeAttr("style");
                $('#multipleCountries').removeClass('active');
                $('input:radio[value="Italy"]').prop('checked', true);
                $('#databundle_topup_location').val('Italy').trigger('change');

            });

            $("input:radio[name='customers']").change(function () {
                $('.bundle_add_btn_new').css('pointer-events', '');
            });

            const includeSimNewRadio = $('#include_sim_new');
            const dataBundleMsgNew = $('#databundle_topup_msg_new');
            const mobileInput = $('#mob_cus_id_mobile');

            // Add a click event listener to the radio button
            includeSimNewRadio.on('click', function () {
                // Clear the message and empty the input field
                dataBundleMsgNew.text('');
                mobileInput.val('');
            });

            $(document).on('click', '.plan-box', function () {

                var planid = $('input[name="text"]:checked').data('planid');
                var bundleCountry = $(".country_select_drop").val();
                var planCode = bundleCountry + $('input[name="text"]:checked').data('planname');
                var mob_cus_id = $("#mob_cus_id_mobile").val();

                $('.total-cost').text($('input[name="text"]:checked').data('bundlerate'));
                $('#click-me').css('pointer-events', 'auto');
                //alert(bundleCountry);
                // AJAX request to fetch the data
                $.ajax({
                    url: "<?php echo $newblock->getRomingAjaxUrl(); ?>", // Replace with the actual URL to your server-side script
                    type: 'POST',
                    data: { planid: planid }, // Pass the 'planid' value to the server
                    dataType: 'JSON',
                    showLoader: true,
                    success: function (response) {
                        if (response.success) {
                            var optionsHtml = response.optionsHtml;
                            $('#databundle_roamingcountries').html(optionsHtml);
                        } else {
                            console.error('Error: ' + response.message);
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.error('AJAX Error: ' + textStatus + ' ' + errorThrown);
                    }
                });
            });
            $("input:radio[name='country']").change(function () {
                var country = $(this).val();
                if ($("#popularCountries").hasClass("active")) {
                    $('#databundle_topup_location').val(country).trigger('change');
                } else {
                    $('#databundle_topup_location_multiple').val(country).trigger('change');
                }
            });
        });
        $("#click-me").click(function () {
            var simType = $('input[name="text"]:checked').data('simtype');
            var supplier = $('input[type="radio"][name="text"]:checked').data('supplier');
            if (supplier == 'E-Sim2Fly') {
                $("#existing-customer").removeClass('d-flex');
                $("#existing-customer").hide();
            } else {
                $("#existing-customer").addClass('d-flex');
                $("#existing-customer").show();
            }
            if (simType == "eSIM") {
                // display none for #esim_button
                document.getElementById("physicalsim_button").style.display = "none";
                document.getElementById("esim_button").style.display = "unset";
            } else if (simType == "Physical Sim") {
                // display none for #physicalsim_button
                document.getElementById("esim_button").style.display = "none";
                document.getElementById("physicalsim_button").style.display = "unset";
            } else {
                document.getElementById("esim_button").style.display = "unset";
                document.getElementById("physicalsim_button").style.display = "unset";
            }

        })


        //Country Change Event for New prices 
        $("#databundle_topup_location,#databundle_topup_location_multiple").change(function () {
            var bundleCountry = $(this).val();
           
            if (bundleCountry != 'Italy' && bundleCountry != 'Thailand' && bundleCountry != 'Canada' && bundleCountry != 'Mexico' && bundleCountry != 'Turkey' && bundleCountry != 'Germany' && bundleCountry != 'Israel' && bundleCountry != 'Global' && bundleCountry != 'Asia' && bundleCountry != 'Africa' && bundleCountry != 'Europe' && bundleCountry != 'Middle East' && bundleCountry != 'North America' && bundleCountry != 'South America') {
                $('input:radio[name="country"]').prop('checked', false);
            } else {
                $('input:radio[value="' + bundleCountry + '"]').prop('checked', true);
            }
            var bundleRegion = $(this).val();

            $.ajax({
                url: "<?php echo $newblock->getAjaxUrl(); ?>",
                method: 'POST',
                data: {
                    'bundle_country': bundleCountry,
                    'region_code': bundleRegion,
                    'page': 'Data-Bundle-Page'
                },
                dataType: 'JSON',
                showLoader: true,
                success: function (result) {
                    if (result.plans !== '') {
                        $(".plan-content").html(result.plans);
                        $('#roamingcountry_autoSelect, #preload').show();
                        $("input[name='bundle_value']").first().trigger("change");
                        var radioButton = $('input[type="radio"][name="text"]:first');
                        radioButton.prop('checked', true).trigger('change');
                        $('.plan-box').trigger('click');
                        $(".country_select_drop").val(bundleCountry);
                    } else {
                        $(".plan-content").html("<div id='error_message' style='color: green;'>Currently No plan for this Country. Please Visit After Some Time....</div>");
                        $('#roamingcountry_autoSelect, #preload').hide();
                    }
                }
            });
        });

        //bundle options click function
        $("body").on("change", "input[name='bundle_value']", function () {
            var convrRate = '<?php echo $StoreConvRate; ?>';
            var currencySymbol = '<?php echo $currencySymbol; ?>';

            var bundle_shortcode = $(this).data('shortcode');
            $('#selected_bundle_shortcode').html(bundle_shortcode);

            var bundle_price = $(this).data('bundlerate');
            var final_selection_price = parseFloat(bundle_price);
            $('#selected_bundle_price').html(currencySymbol + final_selection_price.toFixed(2));

        });

        //Add to cart Button which has all data
        $('.bundle_add_btn_new').click(function (e) {

            e.preventDefault();
            var bundleCountry = $(".country_select_drop").val();
            var supplier = $('input[type="radio"][name="text"]:checked').data('supplier');
            var planCode = bundleCountry + $('input[name="text"]:checked').data('planname');
            var dataBundleClass = '';
            var btnId = '';
            <?php
            if (strpos($url, '/data-bundles') !== false) { ?>  
                var mob_cus_id = $("#mob_cus_id_mobile").val();
                    if (mob_cus_id == '' && $('#mob_cus_id_btn').is(":checked")) {
                        alert("Plese enter Mobile Number or Customer ID");
                        return;
                    }
                    if (mob_cus_id != '') {
                        dataBundleClass = 'data_bundle_topup';
                        btnId = 'bundle_topup_cart_add'
                        var bundle_cat = "D";//Data Bundle Only, VD code for Voice + Data Bundle
                        var pass_puk = "PinLess";
                        $.ajax({
                            url: "<?php echo $this->getUrl(''); ?>customer-check.php",
                            type: 'post',
                            data: { 'mob_cus_id': mob_cus_id, 'pass_puk': pass_puk, 'bundle_cat': bundle_cat, 'page': 'DataBundleTopUp', 'supplier': supplier, 'planCode': planCode },
                            showLoader: true,
                            success: function (result) {
                                if (result.indexOf('ok-to-add-bundle') > -1) {
                                    //Bundle-Is-Valid and add bundle product into cart
                                    $("#databundle_topup_msg_new").html("<span style='color:#67b903; font-weight:bold;'>Please wait, you are being directed to the shopping cart.</span>");
                                    $("input#mob_cus_id_orig").val(mob_cus_id);
                                    $("select.product-custom-option option:contains(" + planCode + ")").attr('selected', 'selected');
                                    $(".country_select_drop").val(bundleCountry);
                                    $("." + btnId).click();


                                } else if (result.indexOf('notvalidate') > -1) {
                                    $("#databundle_topup_msg_new").html("Your details could not be located, please ensure you have typed them correctly").css("color", "red");// display error message
                                } else if (result.indexOf('Bundle-Not-Valid') > -1 || result.indexOf('UR')) {
                                    if (supplier != 'Go') {
                                        $("#databundle_topup_msg_new").html("Bundle is NOT valid on your current SIM, please purchase our new SIM card <a href='https://www.worldsim.com/data-sim-card'>here</a>");// display error message
                                    }else{
                                        $("#databundle_topup_msg_new").html("This bundle is valid on eSIM only, please select new eSIM option");// display error message
                                    }
                                } else if (result.indexOf('Voice-Bundle-Selected-Over-Data-SIM') > -1) {
                                    $("#databundle_topup_msg_new").html("You cannot buy Voice Bundle over Data SIM Card.");// display error message
                                }
                            }
                        });
                    } else if ($('#include_sim_new').is(":checked")) {
                        var activeButton = $('.rightBar .simBtn.active');
                        if (activeButton.attr('id') === 'esim_button') {
                            dataBundleClass = 'data_bundle_new_e_sim';
                            btnId = 'new_esimcard_cart_add';
                        } else if (activeButton.attr('id') === 'physicalsim_button') {
                            dataBundleClass = 'data_bundle_new_physical_sim';
                            btnId = 'new_simcard_cart_add';
                        }
                        $(".country_select_drop").val(bundleCountry);
                        $("select.product-custom-option option:contains(" + planCode + ")").attr('selected', 'selected');
                        $("." + btnId).click();
                    }
            <?php } else { //if not data bundle page ?>
                    $(".country_select_drop").val(bundleCountry);
                    $("select.product-custom-option option:contains("+ planCode + ")").attr('selected', 'selected');
                $(".bundle_topup_cart_add").click();
            <?php } ?>
    });
});
</script>