<?php

$_product = $this->getProduct();

?>
<?php if($_product->getData('features_heading_1')): ?>
<div class="container d-none d-lg-block">
    <h2 class="heading text-uppercase text-center mt-5 mb-5">Features</h2>
	
    <ul class="nav nav-tabs" id="features-tab" role="tablist">
	<?php if($_product->getData('features_heading_1')): ?>
        <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#features1" role="tab"
                aria-controls="features1" aria-selected="true" style="">
                <img class="<?php echo $_product->getData('features_icon_1'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_1'); ?>">
					<span> <?php echo $_product->getData('features_heading_1'); ?></span>
					</a>
		</li>

	<?php endif; ?>
	<?php if($_product->getData('features_heading_2')): ?>
		
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#features2" role="tab"
                aria-controls="features2" aria-selected="true" style="">
                <img class="<?php echo $_product->getData('features_icon_2'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_2'); ?>">
					<span> <?php echo $_product->getData('features_heading_2'); ?></span>
					</a>
		</li> 

<?php endif; ?>
	<?php if($_product->getData('features_heading_3')): ?>
		
        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#features3" role="tab"
                aria-controls="features3" aria-selected="true" style="">
                <img class="<?php echo $_product->getData('features_icon_3'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_3'); ?>">
					<span> <?php echo $_product->getData('features_heading_3'); ?></span>
					</a>
		</li>  

<?php endif; ?>
	<?php if($_product->getData('features_heading_4')): ?>

		<li class="nav-item">
		<a class="nav-link" data-toggle="tab" href="#features4" role="tab"
                aria-controls="features4" aria-selected="true" style="">
				<img class="<?php echo $_product->getData('features_icon_4'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_4'); ?>">
					<span> <?php echo $_product->getData('features_heading_4'); ?></span>
				</a>
		</li>
		
		<?php endif; ?>
	<?php if($_product->getData('features_heading_5')): ?>
		
		<li class="nav-item">
		<a class="nav-link" data-toggle="tab" href="#features5" role="tab"
                aria-controls="features5" aria-selected="true" style="">
				<img class="<?php echo $_product->getData('features_icon_5'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_5'); ?>">
					<span> <?php echo $_product->getData('features_heading_5'); ?></span>
				</a>
		</li>
				
		<?php endif; ?>
	<?php if($_product->getData('features_heading_6')): ?>
	
		<li class="nav-item">
		<a class="nav-link" data-toggle="tab" href="#features6" role="tab"
                aria-controls="features6" aria-selected="true" style="">
				<img class="<?php echo $_product->getData('features_icon_6'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_6'); ?>">
					<span> <?php echo $_product->getData('features_heading_6'); ?></span>
				</a>
		</li>
		
				
		<?php endif; ?>
	<?php if($_product->getData('features_heading_7')): ?>
		
		<li class="nav-item">
		<a class="nav-link" data-toggle="tab" href="#features7" role="tab"
                aria-controls="features7" aria-selected="true" style="">
				<img class="<?php echo $_product->getData('features_icon_7'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_7'); ?>">
					<span> <?php echo $_product->getData('features_heading_7'); ?></span>
				</a>
		</li>
		
				
		<?php endif; ?>
	<?php if($_product->getData('features_heading_8')): ?>
		
		<li class="nav-item">
		<a class="nav-link" data-toggle="tab" href="#features8" role="tab"
                aria-controls="features8" aria-selected="true" style="">
				<img class="<?php echo $_product->getData('features_icon_8'); ?>"
                    src="<?php echo $block->getViewFileUrl('images/feature_sprite.png'); ?>"
                    alt="<?php echo $_product->getData('features_heading_8'); ?>">
					<span> <?php echo $_product->getData('features_heading_8'); ?></span>
				</a>
		</li>
		
	<?php endif; ?>
					
    </ul>
    <div class="tab-content">
	
			
	
	<?php if($_product->getData('features_heading_1')): ?>
	
        <div class="tab-pane fade active in" id="features1" role="tabpanel" aria-labelledby="features1">
            <h3><?php echo $_product->getData('features_heading_1'); ?></h3>
            <p><?php echo $_product->getData('features_txt_1'); ?></p>
        </div>
		
		<?php endif; ?>
		<?php if($_product->getData('features_heading_2')): ?>
		
        <div class="tab-pane fade" id="features2" role="tabpanel" aria-labelledby="features2">
            <h3><?php echo $_product->getData('features_heading_2'); ?></h3>
            <p><?php echo $_product->getData('features_txt_2'); ?></p>
        </div>
		
		<?php endif; ?>
		<?php if($_product->getData('features_heading_3')): ?>
		
        <div class="tab-pane fade" id="features3" role="tabpanel" aria-labelledby="features3">
            <h3><?php echo $_product->getData('features_heading_3'); ?></h3>
            <p><?php echo $_product->getData('features_txt_3'); ?></p>
        </div>
		
		<?php endif; ?>
		<?php if($_product->getData('features_heading_4')): ?>
		
        <div class="tab-pane fade" id="features4" role="tabpanel" aria-labelledby="features4">
            <h3><?php echo $_product->getData('features_heading_4'); ?></h3>
            <p><?php echo $_product->getData('features_txt_4'); ?></p>
        </div>
		
		<?php endif; ?>
		<?php if($_product->getData('features_heading_5')): ?>
		
        <div class="tab-pane fade" id="features5" role="tabpanel" aria-labelledby="features5">
            <h3><?php echo $_product->getData('features_heading_5'); ?></h3>
            <p><?php echo $_product->getData('features_txt_5'); ?></p>
        </div>
		
		<?php endif; ?>
		<?php if($_product->getData('features_heading_6')): ?>
		
        <div class="tab-pane fade" id="features6" role="tabpanel" aria-labelledby="features6">
            <h3><?php echo $_product->getData('features_heading_6'); ?></h3>
            <p><?php echo $_product->getData('features_txt_6'); ?></p>
        </div>
		
		<?php endif; ?>
		<?php if($_product->getData('features_heading_7')): ?>
		
        <div class="tab-pane fade" id="features7" role="tabpanel" aria-labelledby="features7">
            <h3><?php echo $_product->getData('features_heading_7'); ?></h3>
            <p><?php echo $_product->getData('features_txt_7'); ?></p>
        </div>
		
		<?php endif; ?>
		<?php if($_product->getData('features_heading_8')): ?>
		
        <div class="tab-pane fade" id="features8" role="tabpanel" aria-labelledby="features8">
            <h3><?php echo $_product->getData('features_heading_8'); ?></h3>
            <p><?php echo $_product->getData('features_txt_8'); ?></p>
        </div>
		
		<?php endif; ?>
    </div>
</div>
<?php endif; ?>

<div class="container d-lg-none">

    <div id="accordion" class="nav-tabs my-5">
        <?php if($_product->getData('features_heading_1')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseOne">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_1'); ?></span>
                </a>
            </div>
            <div id="collapseOne" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_1'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_1'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getData('features_heading_2')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseTwo">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_2'); ?></span>
                </a>
            </div>
            <div id="collapseTwo" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_2'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_2'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getData('features_heading_3')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseThree">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_3'); ?></span>
                </a>
            </div>
            <div id="collapseThree" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_3'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_3'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getData('features_heading_4')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseFour">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_4'); ?></span>
                </a>
            </div>
            <div id="collapseFour" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_4'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_4'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getData('features_heading_5')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseFive">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_5'); ?></span>
                </a>
            </div>
            <div id="collapseFive" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_5'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_5'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getData('features_heading_6')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseSix">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_6'); ?></span>
                </a>
            </div>
            <div id="collapseSix" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_6'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_6'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getData('features_heading_7')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseSeven">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_7'); ?></span>
                </a>
            </div>
            <div id="collapseSeven" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_7'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_7'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
        <?php if($_product->getData('features_heading_8')): ?>
        <div class="card">
            <div class="card-header">
                <a class="card-link" data-toggle="collapse" href="#collapseEight">
                    <span class="font-size-14"><?php echo $_product->getData('features_heading_8'); ?></span>
                </a>
            </div>
            <div id="collapseEight" class="collapse" data-parent="#accordion">
                <div class="card-body">
                    <h3><?php echo $_product->getData('features_heading_8'); ?></h3>
                    <p><?php echo $_product->getData('features_txt_8'); ?></p>
                </div>
            </div>
        </div>
        <?php endif; ?>
       
    </div>

</div>