<div class="container">
<h3 class="heading text-center mb-5">These are our UK national tariffs</h3>
	<ul class="d-flex ">
		<li>
			<img src="<?php echo $block->getViewFileUrl('images/sprite.png'); ?>" class="mobileIcon">
			<span>Mobile &amp; Landline</span>
			<div class="nationalRate">10p/MIN</div>
		</li>
		<li>
			<img src="<?php echo $block->getViewFileUrl('images/sprite.png'); ?>" class="voiceIcon">
			<span>Voicemail</span>
			<div class="nationalRate">10p/MIN</div>
		</li>
		<li>
			<img src="<?php echo $block->getViewFileUrl('images/sprite.png'); ?>" class="interIcon">
			<span>Internet</span>
			<div class="nationalRate">5p/MB</div>
		</li>
		<li>
			<img src="<?php echo $block->getViewFileUrl('images/sprite.png'); ?>" class="smsIcon">
			<span>SMS</span>
			<div class="nationalRate">9p/SMS</div>
		</li>
		<li>
			<img src="<?php echo $block->getViewFileUrl('images/sprite.png'); ?>" class="insmsIcon">
			<span>International SMS</span>
			<div class="nationalRate">9p/SMS</div>
		</li>
	</ul>
<h6 class="text-center">We offer cheap international calls &amp; roaming</h6>
</div>